sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: i.chmykh:kfjTXFxdFQxyBbAJ0UtYVqOe#general
deploy:
  provider: heroku
  api_key:
    secure: PEwBlYgPqFqQnC099hWl6EaOFIfhxKVggRYSq4IN7LUX7BanevOu6v3Fi5pUz9U//fhP00e0QPDj7s1bAGP0GtSqXIKBiavpI27NNpcyKy3lTF4g0V0sh/WhHAeyNcELOcZ3bHEG+ap3Qzi4f5l7dUDPNwYnjPjrXql+bVrngJqw5IlTr8vEEwXKTebQ6AU4TKaxDnwf4MMpeiX/NlK6RK7quY5uXnzwkto4/rs5y6wLjZGnKhwFsywOenDqVF/IiwzHtLch9bbg05N7tf8KsKBQEsBTy4dk+IyqCTEmyVtmcIuFEqLAfbIVL+d/TdCHj4lqKKWfJcyADbsyeX0UlTcy4GKVOX52KM3GFHzTIJaO04lexuHR0B2802kQx8XGJh6kNhpjNXjvs1MYYiaIv1Xbc0Aa5Z+umhS1S/NWCiKDTXURlaxcYvHGrfvWSE1VWApkT3mCROqygPw+ssAqWLHyQZpY+akHDMaGR0OjTl1fHMJchx21o9V8X2L96R9XhdxmUQlbJcvt9+N5WTqRsCqfRM4WcC/oBWZGYtAAIFb09A241sLSZe1VmXidGFv1tINh7vUei2PsmTXLgX38i53Pb4FyAo+0Y6+BcksoW6rhmDHqvw9BugMIS3E0ukMTVw9vFXHstCvRQR1ko5LJN/OkHO56EM0pE1xadxMPLLY=
  app: evening-sierra-54559
  on:
    repo: visor86/delivery-pipeline-training
